steps:
## Shinkwrap
- name: 'gcr.io/$PROJECT_ID/faas-cli:0.8.8'
  args: ['faas-cli', 'template', 'store', 'pull', 'golang-http']
- name: 'gcr.io/$PROJECT_ID/faas-cli:0.8.8'
  args: ['faas-cli', 'build', '--shrinkwrap']
## Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world-go:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/hello-world-go:latest', '-f' ,'./build/hello-world/Dockerfile', './build/hello-world/']

# Deploy to "Cloud Run"
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'hello-world-go', '--image', 'gcr.io/$PROJECT_ID/hello-world-go:$REVISION_ID', '--region', 'us-central1']

images:
- 'gcr.io/$PROJECT_ID/hello-world-go'
