provider:
  name: faas
  gateway: https://gateway.ofc.matiaspan.me
functions:
  hello-world:
    lang: golang-http
    handler: ./hello-world
    image: hello-world
    environment:
      test: "test"
